"""Create submission table

Revision ID: 254e4cceb2b8
Revises: 85997417c884
Create Date: 2026-09-25 23:10:25.860011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254e4cceb2b8'
down_revision = '85997417c884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('passed', 'failed', name='submissionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('error_category', sa.String(length=40), nullable=True),
    sa.Column('execution_ms', sa.Integer(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name=op.f('fk_submission_challenge_id_challenge')),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], name=op.f('fk_submission_party_id_party')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission'))
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.create_index('ix_submission_party_id_challenge_id', ['party_id', 'challenge_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index('ix_submission_party_id_challenge_id')

    op.drop_table('submission')
    # ### end Alembic commands ###
