"""Add rating to hints

Revision ID: 2a8a78d9c875
Revises: c79cbe6a89c8
Create Date: 2026-09-29 06:47:00.592591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8a78d9c875'
down_revision = 'c79cbe6a89c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hint', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
