"""Create hint, coach message, and AI usage tables

Revision ID: 460665a4b62f
Revises: 738959dd81fc
Create Date: 2026-09-28 15:22:23.977074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460665a4b62f'
down_revision = '738959dd81fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('feature', sa.String(length=20), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], name=op.f('fk_ai_usage_party_id_party')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage')),
    sa.UniqueConstraint('party_id', 'usage_date', 'feature', name=op.f('uq_ai_usage_party_id_usage_date_feature'))
    )
    op.create_table('hint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('ai', 'fallback', name='contentsource', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name=op.f('fk_hint_challenge_id_challenge')),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], name=op.f('fk_hint_party_id_party')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hint'))
    )
    with op.batch_alter_table('hint', schema=None) as batch_op:
        batch_op.create_index('ix_hint_party_id_challenge_id', ['party_id', 'challenge_id'], unique=False)

    op.create_table('coach_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('explanation', 'chat', 'review', 'summary', name='coachmessagekind', native_enum=False, length=20), nullable=False),
    sa.Column('sender', sa.Enum('learner', 'coach', name='messagesender', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('ai', 'fallback', name='contentsource', native_enum=False, length=20), nullable=False),
    sa.Column('rating', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name=op.f('fk_coach_message_challenge_id_challenge')),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], name=op.f('fk_coach_message_party_id_party')),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], name=op.f('fk_coach_message_submission_id_submission')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_message'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coach_message')
    with op.batch_alter_table('hint', schema=None) as batch_op:
        batch_op.drop_index('ix_hint_party_id_challenge_id')

    op.drop_table('hint')
    op.drop_table('ai_usage')
    # ### end Alembic commands ###
