"""Create saved code table

Revision ID: 738959dd81fc
Revises: 254e4cceb2b8
Create Date: 2026-09-25 23:53:13.381794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738959dd81fc'
down_revision = '254e4cceb2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name=op.f('fk_saved_code_challenge_id_challenge')),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], name=op.f('fk_saved_code_party_id_party')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_code')),
    sa.UniqueConstraint('party_id', 'challenge_id', name=op.f('uq_saved_code_party_id_challenge_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_code')
    # ### end Alembic commands ###
