"""Create learner badge table

Revision ID: 83c683517e0c
Revises: 460665a4b62f
Create Date: 2026-09-28 17:13:26.136056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c683517e0c'
down_revision = '460665a4b62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner_badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('badge_code', sa.String(length=80), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], name=op.f('fk_learner_badge_party_id_party')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner_badge')),
    sa.UniqueConstraint('party_id', 'badge_code', name=op.f('uq_learner_badge_party_id_badge_code'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learner_badge')
    # ### end Alembic commands ###
