"""Create challenge tables

Revision ID: 85997417c884
Revises: 981795469a2c
Create Date: 2026-09-25 22:21:51.039630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85997417c884'
down_revision = '981795469a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic')),
    sa.UniqueConstraint('name', name=op.f('uq_topic_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_topic_slug'))
    )
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('beginner', 'intermediate', 'advanced', name='difficulty', native_enum=False, length=20), nullable=False),
    sa.Column('xp_value', sa.Integer(), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=False),
    sa.Column('reference_solution', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'unpublished', name='challengestatus', native_enum=False, length=20), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['party.id'], name=op.f('fk_challenge_author_id_party')),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name=op.f('fk_challenge_topic_id_topic')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenge')),
    sa.UniqueConstraint('slug', name=op.f('uq_challenge_slug'))
    )
    op.create_table('fallback_hint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name=op.f('fk_fallback_hint_challenge_id_challenge')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fallback_hint'))
    )
    op.create_table('test_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name=op.f('fk_test_case_challenge_id_challenge')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_case'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_case')
    op.drop_table('fallback_hint')
    op.drop_table('challenge')
    op.drop_table('topic')
    # ### end Alembic commands ###
