"""Create identity tables

Revision ID: 981795469a2c
Revises: 
Create Date: 2026-09-25 17:29:35.035230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981795469a2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_type', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_party'))
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('leaderboard_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['party.id'], name=op.f('fk_person_id_party')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person')),
    sa.UniqueConstraint('email', name=op.f('uq_person_email'))
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.Enum('learner', 'instructor', 'system_administrator', name='roletype', native_enum=False, length=30), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granted_by_party_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_party_id'], ['party.id'], name=op.f('fk_role_granted_by_party_id_party')),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], name=op.f('fk_role_party_id_party')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('party_id', 'role_type', name=op.f('uq_role_party_id_role_type'))
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], name=op.f('fk_user_account_party_id_party')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account')),
    sa.UniqueConstraint('party_id', name=op.f('uq_user_account_party_id'))
    )
    op.create_table('learner_profile',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_learner_profile_person_id_person')),
    sa.PrimaryKeyConstraint('person_id', name=op.f('pk_learner_profile'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learner_profile')
    op.drop_table('user_account')
    op.drop_table('role')
    op.drop_table('person')
    op.drop_table('party')
    # ### end Alembic commands ###
