"""Create daily mission table

Revision ID: c79cbe6a89c8
Revises: 83c683517e0c
Create Date: 2026-09-28 17:21:40.278342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79cbe6a89c8'
down_revision = '83c683517e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('mission_date', sa.Date(), nullable=False),
    sa.Column('template', sa.String(length=30), nullable=False),
    sa.Column('target', sa.String(length=60), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Integer(), nullable=False),
    sa.Column('bonus_xp', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], name=op.f('fk_daily_mission_party_id_party')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_mission')),
    sa.UniqueConstraint('party_id', 'mission_date', 'template', name=op.f('uq_daily_mission_party_id_mission_date_template'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_mission')
    # ### end Alembic commands ###
